apiVersion: v1
kind: Service
metadata:
  name: awards-app-service
  namespace: awards
spec:
  type: LoadBalancer
  selector:
    pod: awards-app
  ports:
  - protocol: TCP
    port: 1111
    targetPort: 1111
    nodePort: 30001