apiVersion: v1
kind: Service
metadata:
  name: follow-up-app-service
  namespace: follow-up
spec:
  type: LoadBalancer
  selector:
    pod: follow-up-app
  ports:
  - protocol: TCP
    port: 3333
    targetPort: 3333
    nodePort: 30003