apiVersion: v1
kind: Service
metadata:
  name: user-analytics-zipkin-service
  namespace: user-analytics
spec:
  selector:
    pod: user-analytics-zipkin
  ports:
  - protocol: TCP
    port: 9411
    targetPort: 9411