services:
  admin-portal-app:
    container_name: admin-portal-app-service
    image: sahilphule0710/admin-portal:latest
    # build:
    #   context: ../app
    #   dockerfile: Dockerfile
    restart: always
    # volumes:
    #   - ../app:/app
    ports:
      - 3000:3000
    env_file:
      - ./.env