apiVersion: v1
kind: Service
metadata:
  name: reancare-app-service
  # namespace: reancare
spec:
  type: LoadBalancer
  selector:
    pod: reancare-app
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30005