apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: follow-up-mongo-pvc
  namespace: follow-up
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi