apiVersion: v1
kind: Service
metadata:
  name: careplan-app-service
  namespace: careplan
spec:
  type: LoadBalancer
  selector:
    pod: careplan-app
  ports:
  - protocol: TCP
    port: 2222
    targetPort: 2222
    nodePort: 30002