apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-analytics-mysql-pvc
  namespace: user-analytics
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi