apiVersion: v1
kind: PersistentVolume
metadata:
  name: careplan-mysql-pv
  namespace: careplan
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /home/docker/careplan/db