apiVersion: v1
kind: Service
metadata:
  name: forms-service
  namespace: forms
spec:
  type: LoadBalancer
  selector:
    pod: forms-service
  ports:
  - protocol: TCP
    port: 5555
    targetPort: 5555
    nodePort: 30002