apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: awards-mysql-pvc
  namespace: awards
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi