apiVersion: v1
kind: PersistentVolume
metadata:
  name: user-analytics-mysql-pv
  namespace: user-analytics
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /home/docker/user-analytics/db