apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reancare-mysql-pvc
  # namespace: reancare
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi