apiVersion: v1
kind: Service
metadata:
  name: form-builder-service
  namespace: forms
spec:
  type: LoadBalancer
  selector:
    pod: form-builder
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30001