apiVersion: apps/v1
kind: Deployment
metadata:
  name: follow-up-mongo-deployment
  namespace: follow-up
  labels:
    deployment: follow-up-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: follow-up-mongo
  template:
    metadata:
      labels:
        pod: follow-up-mongo
    spec:
      restartPolicy: Always
      containers:
      - name: follow-up-mongo
        image: mongo:latest
        ports:
        - containerPort: 27017
        envFrom:
        - configMapRef:
            name: follow-up-configmap
        - secretRef:
            name: follow-up-secrets
        volumeMounts:
        - name: mongo-volume
          mountPath: /data/db
      volumes:
      - name: mongo-volume
        persistentVolumeClaim:
          claimName: follow-up-mongo-pvc