apiVersion: v1
kind: Service
metadata:
  name: follow-up-mongo-service
  namespace: follow-up
spec:
  selector:
    pod: follow-up-mongo
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017