apiVersion: v1
kind: Service
metadata:
  name: reancare-app-service
  # namespace: reancare
spec:
  type: LoadBalancer
  selector:
    pod: reancare-app
  ports:
  - protocol: TCP
    port: 7272
    targetPort: 7272
    nodePort: 30005