apiVersion: v1
kind: PersistentVolume
metadata:
  name: awards-mysql-pv
  namespace: awards
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /home/docker/awards/db