apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: careplan-mysql-pvc
  namespace: careplan
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi