apiVersion: v1
kind: Service
metadata:
  name: careplan-mysql-service
  namespace: careplan
spec:
  selector:
    pod: careplan-mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
    