apiVersion: v1
kind: PersistentVolume
metadata:
  name: reancare-mysql-pv
  # namespace: reancare
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /home/docker/reancare/db