apiVersion: apps/v1
kind: Deployment
metadata:
  name: forms-service-mysql-deployment
  namespace: forms
  labels:
    deployment: forms-service-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: forms-service-mysql
  template:
    metadata:
      labels:
        pod: forms-service-mysql
    spec:
      restartPolicy: Always
      containers:
      - name: forms-service-mysql-container
        image: mysql:latest
        ports:
        - containerPort: 3306
        envFrom:
        - configMapRef:
            name: forms-service-configmap
        - secretRef:
            name: forms-service-secrets
        volumeMounts:
        - name: mysql-volume
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-volume
        persistentVolumeClaim:
          claimName: forms-service-mysql-pvc