apiVersion: v1
kind: PersistentVolume
metadata:
  name: forms-service-mysql-pv
  namespace: forms-service
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /home/docker/forms-service/db