apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forms-service-mysql-pvc
  namespace: forms
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi