apiVersion: v1
kind: Service
metadata:
  name: forms-service-mysql-service
  namespace: forms
spec:
  selector:
    pod: forms-service-mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
    